import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "../views/Navbar";
import Sidebar from "../views/Sidebar";

const heading = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["600", "700"],
});

const body = Inter({ variable: "--font-inter", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Beakery and cafe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${body.variable} ${heading.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div className="flex flex-col flex-1">
          <div>
            <Navbar />
          </div>

          <div className="flex flex-1">
            <Sidebar />
            <main className="flex flex-1">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
